name: Update MVS EPG XMLTV

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG Converter
        env:
          CHANNEL_IDS: "807,808,809"  # Or use repo secrets/env for dynamic list
        run: |
          python mvshub-epg-generator.py "$CHANNEL_IDS"

      - name: Commit and push XML
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epgmvs.xml
          git diff --staged --quiet || git commit -m "Update EPG XMLTV $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
